### ISSUE TITLE
URL support for createff

### ISSUE THREAD

**Issue by Vizis** [Pixelmon-Development/AdvancedHolograms#4]
Could you add support for creating holograms from file from URL? i have all my server databases on my small vps so i could make there rankings from mysql savedto .txt and then imported by a holograms from diffrent machine

**Comment by danorris709** [comment]
I won't be implementing a feature like this into the mod. The main reason being that if you want to download files to your machine you can use something such as the curl command or another tool for your specific platform. In addition to this, it gets more complicated when you consider different issues such as passwords, or SSH keys required to download files form any given hardware. 

I hope that the reasoning has provided a useful alternative for solving your issue here.

**Comment by Vizis** [comment]
none of the above can solve it. It's not hard to imlement simple reading file/url, there are no need to download anything. Seems when i find more time i ll just implement it by my self using ur source code.
